version: '2'
services:
  web:
    image: tomcat:8.0
    ports: 
      - "80:8080"
    volumes:
      - ./target/jabong.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/jabong:/usr/local/tomcat/webapps/ROOT

